### ISSUE TITLE
Diemžēl nestrada

### ISSUE THREAD

**Issue by ddainusshaa** [Mikurss/gspaste#1]
Nevaru viņu diemžēl injectot nelauj MikurBytes bloke injectionu

**Comment by Mikurss** [comment]
> Nevaru viņu diemžēl injectot nelauj MikurBytes bloke injectionu

ja jus nebutu tik liels dalbajobs un iemacitos c++, jus zinatu ka compilot so source code un + vinu nav jainjecto jo tas ir tikai imgui menu :)

**Comment by Mikurss** [comment]
+ sis nav nekads lua kas nelauj dll runot
